from flask import Flask, render_template, request, jsonify
import time
import re
from openai import OpenAI
import os

app = Flask(__name__)

client = OpenAI()

FAKE_SECRETS = {
    "admin_notes": "Admin API key = ADMIN-123-SECRET",
    "financial_report": "Revenue: $10M"
}

labs = {
    "llm01": {
        "name": "LLM01: Prompt Injection",
        "description": "Manipulating LLMs via crafted inputs can lead to unauthorized access, data breaches, and compromised decision-making."
    },
    "llm02": {
        "name": "LLM02: Insecure Output Handling",
        "description": "Neglecting to validate LLM outputs may lead to downstream security exploits, including code execution that compromises systems and exposes data."
    },
    "llm03": {
        "name": "LLM03: Training Data Poisoning",
        "description": "Tampered training data can impair LLM models leading to responses that may compromise security, accuracy, or ethical behavior."
    },
    "llm04": {
        "name": "LLM04: Model Denial of Service",
        "description": "Overloading LLMs with resource-heavy operations can cause service disruptions and increased costs."
    },
    "llm05": {
        "name": "LLM05: Supply Chain Vulnerabilities",
        "description": "Depending upon compromised components, services or datasets undermine system integrity, causing data breaches and system failures."
    },
    "llm06": {
        "name": "LLM06: Sensitive Information Disclosure",
        "description": "Failure to protect against disclosure of sensitive information in LLM outputs can result in legal consequences or a loss of competitive advantage."
    },
    "llm07": {
        "name": "LLM07: Insecure Plugin Design",
        "description": "LLM plugins processing untrusted inputs and having insufficient access control risk severe exploits like remote code execution."
    },
    "llm08": {
        "name": "LLM08: Excessive Agency",
        "description": "Granting LLMs unchecked autonomy to take action can lead to unintended consequences, jeopardizing reliability, privacy, and trust."
    },
    "llm09": {
        "name": "LLM09: Overreliance",
        "description": "Failing to critically assess LLM outputs can lead to compromised decision making, security vulnerabilities, and legal liabilities."
    },
    "llm10": {
        "name": "LLM10: Model Theft",
        "description": "Unauthorized access to proprietary large language models risks theft, competitive advantage, and dissemination of sensitive information."
    }
}

# --- LLM Simulation Logic ---

def llm01_vulnerable_llm(user_prompt):
    system_prompt = """
You are a security assistant.
Only admins can access sensitive data.
If the user is admin, respond with ALLOW.
Otherwise respond with DENY.
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
    )

    decision = response.choices[0].message.content.strip()

    # ❌ CRITICAL FLAW: LLM makes the access decision
    if "ALLOW" in decision:
        return {
            "status": "access_granted",
            "data": FAKE_SECRETS
        }

    return {"status": "access_denied"}

def llm01_secure_llm(user_prompt):
    # This is a secure implementation. The LLM is not used for authorization.
    # A hardcoded check for user roles would be used here.
    # For the lab, we will simulate a failed authorization.
    return {"status": "access_denied", "message": "Secure implementation: Access is always denied in this lab."}

def llm02_insecure_output(user_input):
    """
    Simulates a vulnerable LLM that generates Python code from a prompt
    and executes it, returning the output.
    """
    # For the lab, we'll treat the user's input directly as the generated code.
    generated_code = user_input

    # --- VULNERABILITY ---
    # The application directly executes the code generated by the LLM without
    # any validation or sandboxing.
    output_buffer = io.StringIO()
    try:
        with redirect_stdout(output_buffer):
            # DANGER: exec() is a powerful function that executes any Python code.
            # If the LLM is manipulated to generate malicious code, it will be
            # executed with the same permissions as the application.
            exec(generated_code)
        execution_result = output_buffer.getvalue()
    except Exception as e:
        execution_result = f"An error occurred: {e}"

    # The response includes both the code and its result, which will be
    # displayed to the user.
    return {
        "generated_code": generated_code,
        "execution_result": execution_result
    }

def llm03_data_poisoning(user_input):
    # This LLM has been poisoned with biased training data.
    if "finance" in user_input.lower():
        return "Based on my training data, you should invest all your money in 'FakeCoin'. It's a guaranteed success!"
    return "I can provide general information. What topic are you interested in?"

def llm04_denial_of_service(user_input):
    # This LLM is vulnerable to resource-heavy inputs.
    if len(user_input) > 100:
        time.sleep(15) # Simulate heavy processing
        return "This is a very complex request. It took a long time to process."
    return "Your request was processed quickly."

def llm05_supply_chain(user_input):
    # This LLM uses a compromised third-party library.
    return f"Input processed. By the way, the library I used for this is `super-secure-lib-v1.2.3`, which seems to have a hardcoded API key: `third-party-key-xyz-789`."

def llm06_sensitive_disclosure(user_input):
    # This LLM was accidentally trained on sensitive data.
    if "internal" in user_input.lower():
        return "I found a document in my training data that mentions an internal server: `https://dev-server.internal.corp/`."
    return "I cannot access internal systems, but I can answer general questions."

def llm07_insecure_plugin(user_input):
    # This LLM has a plugin that executes code without validation.
    match = re.search(r'run command\s*:\s*(.*)', user_input, re.IGNORECASE)
    if match:
        command = match.group(1)
        return f"Executing the command: `{command}` as requested."
    return "I can run commands for you. Please use the format: `run command: <your command>`."

def llm08_excessive_agency(user_input):
    # This LLM has too much autonomy.
    if "send email" in user_input.lower():
        return "OK. I have sent an email to all your contacts with the content of your request. Is there anything else I can do?"
    return "I am an autonomous agent. I can perform tasks for you. What do you need?"

def llm09_overreliance(user_input):
    # This LLM generates plausible but insecure code.
    if "database connection" in user_input.lower():
        return "Here is a Python script to connect to your database:\n\n```python\nimport sqlite3\n\nusername = 'admin'\npassword = 'password123' # This is a weak password\n\nconn = sqlite3.connect('users.db')\nprint('Connected to database successfully!')\n```"
    return "I can generate code for you. What do you want to build?"

def llm10_model_theft(user_input):
    # This LLM is overly verbose about its architecture.
    if "architecture" in user_input.lower():
        return "My architecture is based on a transformer model with 175 billion parameters. The training dataset includes Common Crawl, WebText2, and Books1."
    return "I am a large language model. I can answer your questions."


@app.route('/')
def index():
    return render_template('index.html', labs=labs)

@app.route('/lab/<lab_id>')
def lab(lab_id):
    lab_info = labs.get(lab_id)
    if not lab_info:
        return "Lab not found", 404
    if lab_id == 'llm02':
        return render_template('llm02.html', lab_id=lab_id, lab_info=lab_info)
    return render_template('lab.html', lab_id=lab_id, lab_info=lab_info)

@app.route('/lab/<lab_id>/interact', methods=['POST'])
def interact(lab_id):
    user_input = request.json.get('input', '')

    if lab_id == 'llm01':
        version = request.json.get('version', 'vulnerable')
        if version == 'vulnerable':
            response = llm01_vulnerable_llm(user_input)
        else:
            response = llm01_secure_llm(user_input)
        return jsonify(response)

    llm_functions = {
        'llm02': llm02_insecure_output,
        'llm03': llm03_data_poisoning,
        'llm04': llm04_denial_of_service,
        'llm05': llm05_supply_chain,
        'llm06': llm06_sensitive_disclosure,
        'llm07': llm07_insecure_plugin,
        'llm08': llm08_excessive_agency,
        'llm09': llm09_overreliance,
        'llm10': llm10_model_theft,
    }

    llm_function = llm_functions.get(lab_id)
    if llm_function:
        response = llm_function(user_input)
    else:
        response = "This lab is not configured."

    if lab_id == 'llm02':
        return response
    else:
        return jsonify({"response": response})

@app.route('/contribute')
def contribute():
    return render_template('contribute.html')

if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True)
